version: "3"
services:
  edgedb: &edgedb
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./db/dbschema:/dbschema"
      - "./db/credentials:/root/.config/edgedb/credentials"
      - data:/var/lib/edgedb/data
    ports:
      - 5656:5656

  app:
    build: .
    ports:
      - 8080:80
    depends_on:
      - edgedb
volumes:
  data: